repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 'v4.3.0'
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-builtin-literals
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-yaml
      - id: debug-statements
      - id: requirements-txt-fixer
  - repo: https://github.com/asottile/pyupgrade
    rev: 'v3.1.0'
    hooks:
      - id: pyupgrade
        args:
          - --py38-plus
  - repo: https://github.com/PyCQA/isort
    rev: '5.12.0'
    hooks:
      - id: isort
  - repo: https://github.com/psf/black
    rev: '22.10.0'
    hooks:
      - id: black
  - repo: https://github.com/PyCQA/flake8
    rev: '5.0.4'
    hooks:
      - id: flake8
        args:
        - --show-source
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.21.0
    hooks:
        - id: check-metaschema
          files: ^src/rapids_dependency_file_generator/schema.json$
        - id: check-jsonschema
          files: ^tests/examples/([^/]*)/dependencies.yaml$
          args: ["--schemafile", "src/rapids_dependency_file_generator/schema.json"]
        - id: check-github-workflows
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.4
    hooks:
      - id: ruff
        files: src/.*$
      - id: ruff-format
        files: src/.*$
