on:
  workflow_call:
    inputs:
      release_version:
        type: string

env:
  OUTPUT_DIR: /tmp/output

jobs:
  conda:
    runs-on: ubuntu-latest
    container: condaforge/miniforge3:latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false
      - run: ./ci/build-test/conda.sh
        env:
          RELEASE_VERSION: ${{ inputs.release_version }}
      - uses: actions/upload-artifact@v4
        with:
          name: conda_artifacts
          path: ${{ env.OUTPUT_DIR }}
  docs-build:
    if: github.ref_type == 'branch'
    needs: conda
    runs-on: ubuntu-latest
    container: rapidsai/ci-conda:latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false
      - run: ./ci/build_docs.sh
  wheel:
    runs-on: ubuntu-latest
    container: python:3
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false
      - run: ./ci/build-test/wheel.sh
        env:
          RELEASE_VERSION: ${{ inputs.release_version }}
      - uses: actions/upload-artifact@v4
        with:
          name: wheel_artifacts
          path: ${{ env.OUTPUT_DIR }}
